# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFrdje1ukCQnvzOL3DGxtJtXVKJa-3uZ
"""



"""# Task
Analyze the provided movie dataset to identify trends in viewer ratings and genre popularity, including data loading, cleaning, statistical analysis, visualization, and a summary of insights.

## Load the dataset

### Subtask:
Load the cleaned movie dataset into a pandas DataFrame.

**Reasoning**:
The subtask requires loading the cleaned movie dataset into a pandas DataFrame and displaying its initial rows and information. This can be achieved by importing pandas, reading the CSV file, and then using the `head()` and `info()` methods.
"""

import pandas as pd

# Load the dataset from the file `cleaned_movie_dataset.csv`
df = pd.read_csv('cleaned_movie_dataset.csv')

# Display the first 5 rows of the DataFrame
display(df.head())

# Display the information about the DataFrame
display(df.info())

"""## Handle missing values and duplicates

### Subtask:
Check for and address any missing values and duplicates in the dataset.

**Reasoning**:
Check for missing values and duplicate rows in the DataFrame.
"""

# Check for missing values in each column
missing_values_count = df.isnull().sum()

# Print the count of missing values per column
print("Missing values per column:")
print(missing_values_count)

# Check for duplicate rows
duplicate_rows_count = df.duplicated().sum()

# Print the count of duplicate rows
print(f"\nNumber of duplicate rows: {duplicate_rows_count}")

# Remove duplicate rows if any
if duplicate_rows_count > 0:
    df.drop_duplicates(inplace=True)
    print(f"Removed {duplicate_rows_count} duplicate rows.")

# Verify that duplicate rows have been removed
duplicate_rows_count_after_drop = df.duplicated().sum()
print(f"Number of duplicate rows after removal: {duplicate_rows_count_after_drop}")

"""## Analyze rating distribution

### Subtask:
Calculate and visualize the distribution of movie ratings.

**Reasoning**:
Calculate and visualize the distribution of the 'vote_average' column using a histogram.
"""

import matplotlib.pyplot as plt

# Calculate the distribution of the 'vote_average' column
vote_average_distribution = df['vote_average'].value_counts().sort_index()

# Create a histogram of the 'vote_average' column
plt.figure(figsize=(10, 6))
plt.hist(df['vote_average'], bins=20, edgecolor='black')
plt.xlabel('Vote Average')
plt.ylabel('Frequency')
plt.title('Distribution of Movie Vote Averages')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""## Analyze genre popularity

### Subtask:
Determine the most popular genres based on the dataset.

**Reasoning**:
To determine the most popular genres, I need to extract and count each genre from the 'genres' column, which contains space-separated genre strings.
"""

import collections

# Initialize a Counter to store genre counts
genre_counts = collections.Counter()

# Iterate through the 'genres' column and count each genre
for genres_list in df['genres']:
    # Split the genres string by space
    genres = genres_list.split()
    # Update the counter with the genres from the current movie
    genre_counts.update(genres)

# Convert the genre counts to a pandas Series for easier analysis and sorting
genre_counts_series = pd.Series(genre_counts)

# Sort the genres by their counts in descending order
most_popular_genres = genre_counts_series.sort_values(ascending=False)

# Display the top 10 most popular genres
print("Top 10 Most Popular Genres:")
display(most_popular_genres.head(10))

"""## Analyze ratings by genre

### Subtask:
Explore the relationship between genre and ratings to find which genres have the highest average ratings.

**Reasoning**:
Initialize a dictionary to store total vote average and count for each genre, then iterate through each row of the DataFrame, split the genres, and update the dictionary with the vote average and count for each genre.
"""

genre_ratings = {}

for index, row in df.iterrows():
    genres = row['genres'].split()
    vote_average = row['vote_average']
    for genre in genres:
        if genre not in genre_ratings:
            genre_ratings[genre] = {'total_vote_average': 0, 'count': 0}
        genre_ratings[genre]['total_vote_average'] += vote_average
        genre_ratings[genre]['count'] += 1

"""**Reasoning**:
Calculate the average vote average for each genre, create a pandas Series from the calculated average ratings, sort the genres by their average ratings in descending order, and display the results.


"""

average_genre_ratings = {}
for genre, data in genre_ratings.items():
    if data['count'] > 0:
        average_genre_ratings[genre] = data['total_vote_average'] / data['count']

average_genre_ratings_series = pd.Series(average_genre_ratings)

sorted_genre_ratings = average_genre_ratings_series.sort_values(ascending=False)

print("Average Ratings per Genre (Sorted):")
display(sorted_genre_ratings)

"""## Create visualizations

### Subtask:
Generate visualizations to illustrate rating trends and genre popularity and their relationship.

To download your Colab notebook as a Python file (.py), follow these steps:

1.  Go to the **File** menu in the top left corner of your Colab notebook.
2.  Hover over **Download**.
3.  Click on **Download .py**.

This will download a Python file containing all the code from your notebook cells. You can then open and run this file in VS Code or any other Python environment.

**Reasoning**:
Create bar charts for the top 10 most popular genres and the average ratings per genre.
"""

plt.figure(figsize=(12, 6))
most_popular_genres.head(10).plot(kind='bar', color='skyblue')
plt.xlabel('Genre')
plt.ylabel('Frequency')
plt.title('Top 10 Most Popular Genres')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
sorted_genre_ratings.plot(kind='bar', color='lightgreen')
plt.xlabel('Genre')
plt.ylabel('Average Rating')
plt.title('Average Movie Ratings by Genre')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Summarize insights

### Subtask:
Provide a summary of the key findings from the analysis, including trends in ratings and popular/highly-rated genres.

**Reasoning**:
Summarize the key findings from the analysis, including the distribution of overall movie ratings, genre popularity, and average ratings by genre.
"""

# Summary of Key Findings

# 1. Distribution of Overall Movie Ratings
print("Summary of Overall Movie Rating Distribution:")
print("The histogram of movie vote averages shows a distribution that is roughly bell-shaped but skewed towards higher ratings.")
print("The majority of movies have an average rating between approximately 5.5 and 7.5.")
print("There are fewer movies with very low ratings (below 4) and very high ratings (above 8).")
print(f"\nOverall rating distribution summary:\n{vote_average_distribution.describe()}")

# 2. Genre Popularity
print("\nSummary of Genre Popularity:")
print("The analysis of genre popularity based on frequency reveals that Drama is the most popular genre, followed by Comedy and Thriller.")
print("Action and Romance also appear in the top 5 most popular genres.")
print("Genres like TV Movie, Movie, and unknown are the least frequent in the dataset.")
print("\nTop 10 Most Popular Genres:")
display(most_popular_genres.head(10))

# 3. Relationship between Genre and Ratings
print("\nSummary of Relationship between Genre and Ratings:")
print("Examining the average ratings per genre shows variation in how different genres are rated by viewers.")
print("Genres such as History and War tend to have the highest average ratings.")
print("Conversely, genres like Horror and unknown have the lowest average ratings.")
print("\nAverage Ratings per Genre (Sorted):")
display(sorted_genre_ratings)

print("\nOverall Summary of Insights:")
print("The movie dataset exhibits a concentration of ratings in the mid-range.")
print("While Drama, Comedy, and Thriller are the most popular genres by count, genres like History and War, which are less frequent, receive higher average ratings.")
print("This suggests that popularity does not directly correlate with higher viewer satisfaction as measured by average vote.")

"""## Summary:

### Data Analysis Key Findings

*   The dataset contains 4802 movies with no missing values or duplicate entries.
*   The distribution of movie vote averages is roughly bell-shaped but skewed towards higher ratings, with the majority of movies having an average rating between approximately 5.5 and 7.5.
*   The most popular genres by frequency are Drama, Comedy, and Thriller.
*   Genres such as History and War tend to have the highest average ratings, while genres like Horror and unknown have the lowest average ratings.

### Insights or Next Steps

*   While certain genres are more popular by count (e.g., Drama, Comedy), others that are less frequent (e.g., History, War) receive higher average ratings, suggesting that popularity does not directly correlate with higher viewer satisfaction as measured by average vote.
*   Further analysis could explore if there are specific characteristics within highly-rated but less popular genres that contribute to their higher scores, or investigate the reasons behind lower ratings in popular genres like Horror.

"""